name: 02 - Manually deploy ec2 instance

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}

on:
  workflow_dispatch:
    inputs:
      environmentName:
        description: 'The name of the environment to create.'
        required: true
        default: 'development'

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy EC2
    environment: dev
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'maven'

      - name: NPM install
        run: npm install

      - name: Deploy CDK bootstrap stack
        run: npm run ec2:deploy -- -c environmentName=${{ github.event.inputs.environmentName }}

